
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hksys?characterEncoding=utf8
    username: root
    password: 19960123
    thymeleaf:
      prefix: classpath:/
    resources:
          static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /







